### ISSUE TITLE
Allow unmatched list items

### ISSUE THREAD

**Issue by matsbov** [biodiversitydata-se/specieslist-webapp#3]
Add the possibility to remove the automatic species matching for specific list items.
The process would be like this:

1. You create/upload a list with a "skip-match"-column, defaulting to false.
2. For each item that you then find having gotten an incorrect match, set the "skip-match"-flag to true.
3. Re-match the list. The incorrect matching for the flagged items will be removed and they will become unmatched.
4. If you later on remove the flag, the item will be matched again when you re-match (eg if we update the backbone and you want to try matching again).

**Comment by mathieuLU** [comment]
ok this way is better. 
Having a skip-match column is good, then we can set in advance  the speciesAggregate to "true" since we know they won't be matched

**Comment by mathieuLU** [comment]
right now we found another way to deal with this problem

the "unmatched species" are for us those who end up with the class scientific name ("Aves", "Amphibia"). And we can deal with that.
No need to create a specific way to deal with the unmatched species (like this skip-match column)

What is really important for us, is to make sure that the lists are never unmatched without our validation. But maybe you can't prevent that ? like when you synchronize the gbif taxonomy for instance ?
